<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');

/**
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 *
 * PHP version 5
 * @copyright  Tim Gatzky 2012 
 * @author     Tim Gatzky <info@tim-gatzky.de>
 * @package    Catalog, catalogfieldsMaxChars
 * @license    LGPL 
 * @filesource
 */

$GLOBALS['TL_LANG']['tl_catalog_fields']['maxChars'] = array('Max. characters', 'Please enter the maximum number of characters for this field.');

?>